TMDT/TMDT/Areas/Admin/Controllers/GroupUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using DocumentFormat.OpenXml.Wordprocessing;
using PagedList;
using ProjectSEM3.Common;
using ProjectSEM3.Dao;
using ProjectSEM3.EF;

namespace ProjectSEM3.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class GroupUserController : Controller
    {
        GroupUserDao db = new GroupUserDao();
        // GET: Admin/GroupUser
        public ActionResult Index(string searchString ,  int? page)
        {
            var model = new GroupUserDao();
            int pageSize = 15;
            int pageNumber = 1;
            return View(model.GetAllGroupUsers(searchString).ToPagedList(pageNumber ,pageSize));
        }
        [HttpPost]
        public JsonResult Create(string data)
        {
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            GroupUser model = javaScriptSerializer.Deserialize<GroupUser>(data);

            bool status = false;
            string mess = String.Empty;

            if (model.ID == 0)
            {

                var dao = db.Create(model);
                if (dao == 1)
                {
                    status = true;
                    mess = "Thêm mới thành công";
                }
                else
                {
                    status = false;
                    mess = "Tên đã tồn tại";
                }
           
            }
            else
            {

                status = db.Update(model);
                mess = "Cập nhập thất bại";
            }

            return Json(new
            {
                status = status,
                mess = mess
            });

        }
       

        [HttpPost]
        public JsonResult Delete(long id)
        {
            var model= new GroupUserDao().Delete(id);
            return Json(new
            {
                status = model
            });
        }

        [HttpPost]
        public JsonResult ViewDetail(long id)
        {
            var model = db.ViewDetail(id);
            return Json(new
            {
                status = true,
                id = model.ID
                ,
                name = model.Name
                ,
                des = model.Desciption
            });

        }


    }
}

TMDT/TMDT/Areas/Admin/Views/GroupUser/Create.cshtml
@model ProjectSEM3.EF.GroupUser

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Script
{

}

<div class="x_content">
    <div class="">

        <div class="clearfix"></div>

        <div class="row">


            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">

                        <h2>Tạo quyền</h2>
                        
                        <div class="clearfix"></div>
                    </div>
                    <a href="/Admin/GroupUser/Index/" class="btn btn-default">
                        <img src="~/Assets/Admin/images/Arrow-prevoius-2-icon.png" width="30px" height="30px" />
                    </a>
                    <div class="x_content">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-3 col-sm-3 col-xs-12"})
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control col-md-7 col-xs-12"}})
                                        @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Desciption, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.EditorFor(model => model.Desciption, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                        @Html.ValidationMessageFor(model => model.Desciption, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="clearfix"></div>
                                <div class="form-group">
                                    <div class="col-md-offset-7 col-md-7 col-xs-12">
                                        <input type="submit" value="Thêm" class="btn btn-success" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

TMDT/TMDT/Areas/Admin/Views/GroupUser/Edit.cshtml
@model ProjectSEM3.EF.GroupUser

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Script
{

}

<div class="x_content">
    <div class="">

        <div class="clearfix"></div>

        <div class="row">


            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">

                        <h2>Thêm quyền cho tài khoản</h2>
                        
                        <div class="clearfix"></div>
                    </div>
                    <a href="/Admin/GroupUser/Index/" class="btn btn-default">
                        <img src="~/Assets/Admin/images/Arrow-prevoius-2-icon.png" width="30px" height="30px" />
                    </a>
                    <div class="x_content">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Desciption, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.EditorFor(model => model.Desciption, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                        @Html.ValidationMessageFor(model => model.Desciption, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="clearfix"></div>
                                <div class="form-group">
                                    <div class="col-md-offset-7 col-md-7 col-xs-12">
                                        <input type="submit" value="Cập nhập" class="btn btn-success" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

TMDT/TMDT/Areas/Admin/Views/GroupUser/Index.cshtml
@model PagedList.IPagedList<ProjectSEM3.EF.GroupUser>
@using PagedList.Mvc
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Script{

    <script src="~/Assets/Admin/GroupUserController.js"></script>

}
<div class="x_content">
    <div class="">


        <div class="clearfix"></div>

        <div class="row">


            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Phân quyền tài khoản</h2>
                        
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div id="datatable-checkbox_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <div class="col-sm-6">
                                <div class="dataTables_length" id="datatable-checkbox_length">
                                    <button class="btn btn-default" id="btn-Add">
                                        <img src="~/Assets/Admin/images/Graphicloads-100-Flat-2-Add.ico" width="30px" height="30px" />
                                    </button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                   
                                </div>
                                <div class="col-sm-6">
                                    <div class="title_right">
                                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                            @using (Html.BeginForm("Index", "GroupUser"))
                                            {

                                                <div class="input-group">

                                                    <input type="text" name="searchString" class="form-control" value="@ViewBag.SearchString" placeholder="Tìm kiếm...">
                                                    
                                                </div>
                                            }

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">


                                    <table id="datatable-checkbox" class="table table-striped table-bordered table-hover" role="grid">
                                        <thead>
                                            <tr role="row" class="">

                                                <th>ID</th>
                                                <th>Tên</th>
                                                <th>Mô tả</th>
                                                <th>Hiệu chỉnh</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr role="row" id="row_@item.ID" class="odd">
                                                    <td>@item.ID</td>
                                                    <td>@item.Name</td>
                                                    <td>@item.Desciption</td>
                                                    <td>
                                                        <div class="text-center">
                                                            <a href="#" data-toggle="tooltip" title="Cập nhập" class="btn btn-default btn-Edit" data-id="@item.ID">
                                                                <img src="~/Assets/Admin/images/Edit-validated-icon.png" width="16px" height="16px" />
                                                            </a>
                                                           
                                                            <a href="/Admin/GrantPermission/Index/@item.ID" data-toggle="tooltip" title="Cài đặt các hành động cho nhóm quyền" class="btn btn-default">
                                                                <img src="~/Assets/Admin/images/Graphicloads-100-Flat-2-Settings.ico" width="16px" height="16px" />
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>


                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div>
                                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Modal -->
                        <div class="modal fade" id="myModalNorm" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <button type="button" class="close"
                                                data-dismiss="modal">
                                            <span aria-hidden="true">&times;</span>
                                            <span class="sr-only">Close</span>
                                        </button>
                                        <h4 class="modal-title" id="myModalLabel">
                                            Thêm/Cập nhập
                                        </h4>
                                    </div>

                                    <!-- Modal Body -->
                                    <div class="modal-body">

                                        <form role="form">
                                            <div class="form-group" style="width: 100%">
                                                <label for="exampleInputEmail1">Tên</label>
                                                <input type="text" class="form-control" style="width: 100%"
                                                       id="txtName" />
                                                <input type="hidden" value="0" id="txtID" />
                                            </div>
                                            <div class="form-group" style="width: 100%">
                                                <label for="exampleInputPassword1">Mô tả</label>
                                                <input type="text" class="form-control" style="width: 100%" id="txtDescription"
                                                       placeholder="Liên kết" />
                                            </div>

                                        </form>


                                    </div>

                                    <!-- Modal Footer -->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default"
                                                data-dismiss="modal">
                                            Thoát
                                        </button>
                                        <button type="button" class="btn btn-primary" id="btn-Add-data">
                                            <span class="glyphicon glyphicon-plus"></span>Lưu
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>




            </div>
                </div>

            </div>
        </div>
    </div>
</div>