TMDT/TMDT/Areas/Admin/Controllers/ContentCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using PagedList;
using ProjectSEM3.Common;
using ProjectSEM3.Dao;
using ProjectSEM3.EF;

namespace ProjectSEM3.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class ContentCategoryController : Controller
    {
        ContentCategoryDao db = new ContentCategoryDao();
        // GET: Admin/ContentCategory
        public ActionResult Index(string searchString, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var model = db.GetAll(searchString).ToPagedList(pageNumber, pageSize);
            return View(model);
        }


        [HttpPost]
        public JsonResult Create(string data)
        {
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            ContentCategory model = javaScriptSerializer.Deserialize<ContentCategory>(data);

            bool status = false;
            string mess = String.Empty;

            if (model.ID == 0)
            {
                var dao = db.Create(model);
                if (dao==1)
                {
                    status = true;
                    mess = "Thêm mới thành công";
                }
                else
                {
                    status = false;
                    mess = "Tên đã tồn tại";
                }
                
            }
            else
            {
              
                status = db.Update(model);
                mess = "Cập nhập thất bại";
            }

            return Json(new
            {
                status=status,
                mess = mess
            });

        }

     
        /// <summary>
        /// hàm này dùng để xóa tạm
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult ChangeStatus(long id)
        {
            var dao = db.ChangeStatus(id);
            return Json(new
            {
                status = dao
            });

        }

    

        /// <summary>
        /// cập nhập lại status theo mảng
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>

        [HttpPost]
        public JsonResult DeleteSelected(string ids)
        {
            var model = new ContentCategoryDao();
            var lstID = ids.Split(',');
            bool res = true;
            foreach (var id in lstID)
            {
                long cv = Convert.ToInt64(id);
                res = model.ChangeStatus(cv);
            }
            return Json(new
            {
                status = res
            });
        }


        //thùng rác
        //GET 
        public ActionResult RecycelBin(string searchString, int? page)
        {
            var model = db.GetAllRecycelBin(searchString);
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            ViewBag.SearchString = searchString;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// xóa trong db
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Delete(long id)
        {
            var dao = db.Delete(id);//xóa trong db
            return Json(new
            {
                status = dao//trả về giá trị cho ajax true false
            });

        }


        /// <summary>
        /// xóa mảng thành phần được chọn trong db
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteSelectedDb(string ids)
        {
            var lstID = ids.Split(',');//chuyển chuỗi thành mảng
            bool res = true;
            foreach (var id in lstID)
            {
                long cv = Convert.ToInt64(id);
                res = db.Delete(cv);
            }
            return Json(new
            {
                status = res
            });
        }
        /// <summary>
        /// cập nhập mảng status
        /// </summary>
        /// <param name="ids"></param>
        /// <returns>bool</returns>
        [HttpPost]
        public JsonResult DeleteSelectedRecycelBin(string ids)
        {
            var lstID = ids.Split(',');
            bool res = true;
            foreach (var id in lstID)
            {
                long cv = Convert.ToInt64(id);
                res = db.ChangeStatus(cv);
            }
            return Json(new
            {
                status = res
            });
        }

        [HttpPost]
        public JsonResult ViewDetail(long id)
        {
            var model = db.ViewDetail(id);
            return Json(new
            {
                status = true
                ,id = model.ID,
                name = model.Name,
                url = model.MetaTitle
            },JsonRequestBehavior.AllowGet);
        }

    }
}

TMDT/TMDT/Areas/Admin/Views/ContentCategory/RecycelBin.cshtml
@model PagedList.IPagedList<ProjectSEM3.EF.ContentCategory>
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Script{
    <script src="~/Assets/Admin/ContentCateoryController.js"></script>
    <script src="~/Assets/Admin/ContentCateoryController.js"></script>
}
<div class="x_content">
    <div class="">


        <div class="clearfix"></div>

        <div class="row">


            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Xóa tạm</h2>
                        
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div id="datatable-checkbox_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="dataTables_length" id="datatable-checkbox_length">

                                        
                                        <a href="/Admin/ContentCategory" class="btn btn-default">
                                            <img src="~/Assets/Admin/images/Arrow-prevoius-2-icon.png" width="30px" height="30px" />
                                        </a>
                                        <a href="" class="btn btn-default" id="btn-remove-deleteAll">
                                            <img src="~/Assets/Admin/images/gtk_undelete.png" width="30px" height="30px" />
                                        </a>
                                        <a href="" class="btn btn-default" id="btn-remove-deleteAll-db">
                                            <img src="~/Assets/Admin/images/deletered.png" width="30px" height="30px" />
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="title_right">
                                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                            @using (Html.BeginForm("Index", "ContentCategory"))
                                            {
                                                <div class="input-group">
                                                    <input type="text" name="searchString" class="form-control" value="@ViewBag.SearchString" placeholder="Tìm kiếm...">
                                                    <span class="input-group-btn">
                                                        <button class="btn btn-default" type="submit" style="color: black"><span class="glyphicon glyphicon-search"></span></button>
                                                    </span>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="datatable-checkbox" class="table table-striped table-bordered table-hover" role="grid">
                                        <thead>
                                            <tr role="row" class="">
                                                <th>
                                                    <input type="checkbox" id="checkAll">
                                                    <label for="checkAll"></label>
                                                </th>
                                                <th>ID</th>
                                                <th>Tên</th>
                                                <th>Ngày tạo</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr role="row" id="row_@item.ID" class="odd">
                                                    <td>
                                                        <input type="checkbox" value="@item.ID" name="table_records" id="@item.ID" class="checkbox">
                                                        <label for="@item.ID"></label>
                                                    </td>
                                                    <td>@item.ID</td>
                                                    <td>@item.Name</td>
                                                    <td>
                                                        @item.CreateDate
                                                    </td>
                                                    <td>
                                                        <div class="">
                                                            <a href="#" data-toggle="tooltip" title="Hủy xóa tạm" class="btn btn-default btn-sm btn-remove-delete-contentCaegory  " data-id="@item.ID">
                                                                <img src="~/Assets/Admin/images/undelete.png" width="16px" height="16px" />
                                                            </a>
                                                            <a href="#" data-toggle="tooltip" title="Xóa" class="btn btn-default btn-sm btn-remove-delete-db" data-id="@item.ID">
                                                                <img src="~/Assets/Admin/images/Delete.png" width="16px" height="16px" />
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            }


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                          
                            <div class="row">
                                <div class="col-sm-12">
                                    <div>
                                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>